/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patronmemento;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class PMemento extends javax.swing.JFrame {

    /**
     * Creates new form PMemento
     */
    ArrayList<ArrayList<String>> colores;
    GestorEstado gestor;
    public PMemento() {
        initComponents();
        gestor=new GestorEstado();
        ComboColores.removeAll();
        colores=new ArrayList<>();
        CargarColores();
        CargarCombobox();

        Fondo fondo=new Fondo();
        fondo.setColor("Default", "F0F0F0");
        gestor.agregarMemento(fondo.crearMemento());
    }
    private void CargarColores(){
        ArrayList<String> color;
        
        color=new ArrayList<>();
        color.add("Blanco");
        color.add("FFFFFF");
        colores.add(color);
        
        color=new ArrayList<>();
        color.add("Azul");
        color.add("0000FF");
        colores.add(color);
        
        color=new ArrayList<>();
        color.add("Verde");
        color.add("006400");
        colores.add(color);
        
        color=new ArrayList<>();
        color.add("Rojo");
        color.add("FF0000");
        colores.add(color);
        
        color=new ArrayList<>();
        color.add("Negro");
        color.add("000000");
        colores.add(color);
        
        color=new ArrayList<>();
        color.add("Marron");
        color.add("A52A2A");
        colores.add(color);
        
        color=new ArrayList<>();
        color.add("Celeste");
        color.add("00BFFF");
        colores.add(color);
        
        color=new ArrayList<>();
        color.add("Amarillo");
        color.add("FFFF00");
        colores.add(color);
    }
    private void CargarCombobox(){
        DefaultComboBoxModel modeloCombo=
                (DefaultComboBoxModel)ComboColores.getModel();
        for (int i = 0; i < colores.size(); i++) {
            ArrayList<String> item=(ArrayList<String>)colores.get(i);
            modeloCombo.addElement(item);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboColores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboColores.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Patron Memento");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras(evt);
            }
        });

        btnAdelante.setText("Adelante");
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelante(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboColores, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboColores, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar
        // TODO add your handling code here:
        int posCombo=ComboColores.getSelectedIndex();
        if(posCombo!=-1){
            ArrayList<String> item=(ArrayList<String>)ComboColores.getSelectedItem();
            Color color=new Color(Integer.parseInt(item.get(1),  16 ));
            this.getContentPane().setBackground(color);

            Fondo fondo=new Fondo();
            fondo.setColor(item.get(0), item.get(1));
            gestor.agregarMemento(fondo.crearMemento());
        }
    }//GEN-LAST:event_btnModificar

    private void btnAtras(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras
        // TODO add your handling code here:
        Fondo fondo=new Fondo();
        fondo.setMemento(gestor.Atras());
        if(fondo.estaEstadoCargado()){
            String valor =fondo.getValorColor();
            Color color=new Color(Integer.parseInt(valor,  16 ));
            this.getContentPane().setBackground(color);
        }else{
            JOptionPane.showMessageDialog(null, "Ya no existen estados anteriores");
        }
    }//GEN-LAST:event_btnAtras

    private void btnAdelante(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelante
        // TODO add your handling code here:
        Fondo fondo=new Fondo();
        fondo.setMemento(gestor.Adelante());
        if(fondo.estaEstadoCargado()){
            String valor =fondo.getValorColor();
            Color color=new Color(Integer.parseInt(valor,  16 ));
            this.getContentPane().setBackground(color);
        }else{
            JOptionPane.showMessageDialog(null, "Ya no existen estados posteriores");
        }
    }//GEN-LAST:event_btnAdelante

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PMemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PMemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PMemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PMemento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PMemento().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboColores;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
